#!/usr/bin/env python
import os
import jinja2
import webapp2

from __future__ import division

template_dir = os.path.join(os.path.dirname(__file__), "templates") #crea directorio para incluir templates
jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader(template_dir), autoescape=False)#inicializa Jinja


class BaseHandler(webapp2.RequestHandler):

    def write(self, *a, **kw):
        return self.response.out.write(*a, **kw)

    def render_str(self, template, **params):
        t = jinja_env.get_template(template)
        return t.render(params)

    def render(self, template, **kw):
        return self.write(self.render_str(template, **kw))

    def render_template(self, view_filename, params=None):
        if params is None:
            params = {}
        template = jinja_env.get_template(view_filename)
        return self.response.out.write(template.render(params))

class MainHandler(BaseHandler):
    def get(self):
        return self.render_template("form.html")

    def post(self):
        number_1 = (int(self.request.get("number1"))
        number_2 = (int(self.request.get("number2"))
        operation = self.request.get("operation")

        if operation == "+":
            outcome = number1 + number2

        elif operation == "-":
            outcome = number1 - number2

        elif operation == "*":
            outcome = number1 * number2

        elif operation == "/":
            outcome = number1 / number2

        else:
            print "You didn't select a valid operation."


app = webapp2.WSGIApplication([
    webapp2.Route('/', MainHandler),
    webapp2.Route('/outcome', OutcomeHandler),
], debug=True)
